G = "\033[0;32m"
R = "\033[1;31m"
Y = "\033[0;33m"
import os,sys,time
os.system ("clear")
print (R +"By: Ahmed -El MOGRAM")
print (R +"Team: Věňøm")
A = input (G +"Enter: ")
if A == "1" :
    print (Y +"Steup Termux ")
    time.sleep (2)
    os.system ("clear")
    os.system ("apt update")
    os.system ("apt upgrade")
    os.system ("apt install python && apt install python2 && apt install python3 -y")
    os.system ("apt install ruby -y ")
    os.system ("apt install nano -y")
    os.system ("apt install php -y ")
    os.system ("apt install curl -y")
    os.system ("apt install perl -y")
    os.system ("apt install llvm -y ")
    os.system ("termux-steup-storge -y")
    os.system ("apt install openssl -y")
    os.system ("apt install git -y")
    os.system ("apt install host -y ")
    os.system ("apt install java -y ")
    os.system ("apt install google -y")
    os.system ("apt install bash -y")
    os.system ("apt install  namp -y")
    os.system ("apt install golang -y")
    os.system ("apt install clang -y")
    os.system ("apt install fliget -y")
    os.system ("apt install tar -y")
    os.system ("apt install zip -y")
    os.system ("apt install unzip -y")
    os.system ("apt install tor -y ")
    os.system ("apt install sudo 'y ")
    os.system ("apt install wget -y ")
    os.system ("apt install bomn -y ")
    os.system ("apt insatll cowsay -y")
    os.system ("apt install macchanger -y")
    print (R +"Done💪💪💪💪💪")